---
author: Gabe Macklem
title: Data Scientist
format:
  classic-cv-pdf: default
cvcolor: 58748F #without `#`
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Status
    left: Graduate Assistant Performance Analyst - UNL Football
    right: Lincoln, Nebraska
  - title: Field
    left: Statistics, Data Science
    right: gabem20@comcast.net
  - title: Skills
    left: R, Python, SQL, PowerBI
    right:
execute:
  echo: false
---

```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}
```

# Summary

Driven statistics student with a passionate interest in using statistical methods to enhance sports performance and strategy. Committed to academic excellence and pursuing advanced education opportunities. Recognized for communication abilities and eager to contribute to team success.

# Experience


```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details, ~tasks,
    "Graduate Assistant Performance Analyst",  "University of Nebraska - Lincoln Football", "Aug. 2025 - Present",
    "Department of Sports Sciences", c("Analyzing and modeling data to improve insights on athletic performance, player evaluation, and recruiting"),
    "Intern Data Analyst", "University of Nebraska - Lincoln Football", "Aug. 2024 - Aug. 2025", "Department of Sports Sciences", c("Developed a model that projects athletes' to the NFL", "Estmiated one repetition weights for lifting sessions"),
    "Summer Statistics Research Assistant", "Colorado State University", "May. 2024 - Aug. 2024", "Department of Statistics", c("Advisor: Aaron Nielsen", "Motivated by methods applied in rugby, developed a game difficulty index to inform tactical periodaztion", "NFL Combine Comparison Shiny App"),
    "Precalculus and Statistics Tutor", "Colorado State University", "Jan. 2023 - May 2025", "Mathematics Department and Statistics Department", c("Developing new methods to analyze social networks", "Implementing methods in libraries")
) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "tasks")
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "Statistics MS/PhD", "University of Nebraska - Lincoln", "University of Nebraska - Lincoln", "Aug. 2025 - Present", c("Graduate assistant for football team sports sciences department"),
    "Bachelors of Statistics", "Colorado State University", "Colorado State University", "Aug. 2020 - May 2025", c("Minor: Data Science", "2025 Maurice Davies Award Recipient for Outstanding Undergraduate Achievement", "Dean's List - College of Natural Sciences (Fall '23 - Spring '25)")
) |>
    cvevents(when = "dates", what = "degree", where = "loc", details = "details")

```
